### ISSUE TITLE
Home Page Bugs

### ISSUE THREAD

**Issue by G4be34** [2023-opportunity-hack/CodeFusion-Collective--MobileAppforTeens-RebuildaprototypewithSecurityandUsability#27]
Contact Professional buttons arrow sticks outside of the button in certain screen sizes. 
Button labels are not centered on the buttons

**Comment by HeyMaximus** [comment]
Is this still presented? 
Bug not observed on iOS (2532 × 1170, iPhone14) and Android (1080x2220, Pixel 3a).

**Comment by G4be34** [comment]
This was resolved with PR #49
