### ISSUE TITLE
Warning Signs Page Bugs

### ISSUE THREAD

**Issue by G4be34** [2023-opportunity-hack/CodeFusion-Collective--MobileAppforTeens-RebuildaprototypewithSecurityandUsability#31]
Arrows for drop-down menus go off screen on mobile screen sizes. 
Menu turns blank when clicking the "What is domestic violence?" drop-down menu. 
All the corners of each description box for each section gets cut off when expanded.

**Comment by HeyMaximus** [comment]
Fixed the blank text field in "What is domestic violence?"
Fixed border radius cutting into display. 

The fixes are currently in Maximus3 branch, not yet merge with main.

**Comment by G4be34** [comment]
This issue was resolved with PR #49
